### ISSUE TITLE
Modify the prompt to discourage model from just continuing the utterance

### ISSUE THREAD

**Issue by Ruruthia** [Ruruthia/Questions-answering#2]

**Comment by AdrianUrbanski** [comment]
Czesc!

    On powiedział: Czesc!
    Ona odpowiedziała: 
        Ona odpowiedziała: 
    Ona odpowiedziała:  On powiedział:  On powiedział: Czesc! Ona odpowiedziała: 
        Ona odpowiedziała:  Ona powiedziała
Czy lubisz pierogi?

    On powiedział: Czy lubisz pierogi?
    Ona odpowiedziała: 
        Ona odpowiedział:  Ona powiedziała: Nie sądzę.  ona odpowiedziała: Tak, i nie sądzę. 
        Ona powiedziała:  Chcę tylko powiedzieć,

**Comment by AdrianUrbanski** [comment]
Czesc!

    - Cześsc!
    - 
        w której jest dane z systemu, nie tylko login, lecz również wszystkie pozostałe dane (czy to te które są widoczne jako login).
        do którego można przypisać,
Czy lubisz pierogi?

    - Czy lubisz pierogi?
    - 
        - Czy znasz historię Polski? - Czy znasz polskie legendy? - Na jakiej podstawie się uczysz języka polskiego? - Czy chcesz być na bieżąco?
    - Czy znasz matematykę

**Comment by AdrianUrbanski** [comment]
Czesc 

    On: Cześsc
    Ona: 
        w której jest wszystko to, o co prosic bedzie każdy - a jest to cos wiecej, niz tylko pragnienie.
    On:  Cześć. Ona: To właśnie
dzien dobry

    On: dzien dobry
    Ona: 
      Ona:   ona:  ona: ona:  ona:  Ona:   Ona:   Ona:   Ona:  
    ona:   Ona:   Ona

**Comment by AdrianUrbanski** [comment]
Czesc

    Osoba 1: Czesc
    Osoba 2: 
        W tym przypadku osoba trzecia jest zawsze pierwsza jako wlasciwa do wykonania zadania z danego przedmiotu  
   Osoba 3: Czesc   1: Czesc 2: Czesc
czy lubisz pierogi?

    Osoba 1: czy lubisz pierogi?
    Osoba 2: 
       .       . (       . . ).       . (       . . ).. (       ..
    Osoba

**Comment by AdrianUrbanski** [comment]
Dzień dobry!

    Pytanie: Dzień dobry!
    Odpowiedź: 
        w dniu dzisiejszym mam z żoną i synem wspólny wypad do parku - jedziemy na weekend - mamy ze sobą tylko dwa pokoje, nie mamy telewizora i nie mamy auta. 
    
Czy lubisz pierogi?

    Pytanie: Czy lubisz pierogi?
    Odpowiedź: 
         Jeśli chodzi o muzykę, to na pewno nie słucham jej z płyt, ale uwielbiam się, kiedy jest wykonywana przez kompozytora.
          Jeśli chodzi o muzykę, to
Jakiej muzyki słuchasz?

    Pytanie: Jakiej muzyki słuchasz?
    Odpowiedź: 
        Odbieram ten utwór jako blues, po latach słuchania go chyba też. No i ten wokal jest niesamowity.
        Czy uważasz, że to dobry
Co sądzisz o alpakach?

    Pytanie: Co sądzisz o alpakach?
    Odpowiedź: 
        Pytania: Jakie są wasze przemyślenia na ten temat, czym jest ten alpakowy projekt i jak wygląda realizacja, jakie są Wasze oczekiwania.

**Comment by Ruruthia** [comment]
```
    Beata, odpowiedz na pytanie: Co sądzisz o pierogach?
        M.G.: Nie jest łatwo, jednak można ich przyrządzić wiele razy i zawsze wyjdą pyszne. Mam na myśli pierogi. Myślę, że najlepsze są te ze
```

```
    Beata, odpowiedz na pytanie: Jak Ci diziś minął dzień?
      Beata, odpowiedz na pytanie: Czy chcesz wiedzieć, jak spędziłaś wczoraj wieczór? (na podstawie rozmów, SMS-ów, esemes-ów
```

```
    Beata, odpowiedz na pytanie: Czy na pewno wszystko w porządku?
        W przypadku wątpliwości dotyczących interpretacji przepisu art. 1 ust. 2 pkt 2 lit. a) i b) ustawy, należy zastosować przepisy procedury określonej w ww. para
```

**Comment by Ruruthia** [comment]
```
    On powiedział: Cześć!
    Odpowiedziałem:
        Z Bogiem na Ziemi, że moje ciało i umysł są święte - powiedział Jezus po uzdrowieniu na krzyżu.
        Pozdrowienie miało miejsce zaraz po tej scenie
```
```
    On powiedział: Jak masz na imię?
    Odpowiedziałem:
     W ten sposób uczynili Jezusowi ludzie sługi. Ponieważ wszyscy byli z Nim, więc mogli się ze sobą spotkać. Ponieważ ci sami ludzie byli sługami Abrahama
```

**Comment by AdrianUrbanski** [comment]
https://huggingface.co/blog/gptj-sagemaker#few-shot-example-advanced
